return {
	OverflowMenu = require(script.OverflowMenu),
	Chat = require(script.Chat),
	ConnectUnibar = require(script.Connect.ConnectIconUnibar),
	ConnectDropdown = require(script.Connect.ConnectIconDropdown),
	UnibarMenuToggleButton = require(script.UnibarMenuToggleButtonV2),
	TrustAndSafety = require(script.TrustAndSafety),
	DummyWindow = require(script.DummyWindow),
	DummyWindow2 = require(script.DummyWindow2),
	DummyContainer = require(script.DummyContainer),
	ToggleMic = require(script.ToggleMic),
	JoinVoice = require(script.JoinVoice),
	SelfieView = require(script.SelfieView),
	CameraEntrypoint = require(script.CameraUtility.CameraEntrypoint),
	LikeButton = require(script.MusicUtility.LikeButton),
	MusicEntrypoint = require(script.MusicUtility.MusicEntrypoint),
	Songbird = require(script.MusicUtility.Songbird),
	MusicIcon = require(script.MusicUtility.MusicIcon),
	MusicPlayingIcon = require(script.MusicUtility.MusicPlayingIcon),
	PeekTrackDetails = require(script.MusicUtility.PeekTrackDetails),
	PartyMic = require(script.Party.PartyMic),
	PeekCloseButton = require(script.PeekCloseButton),
	OverflowButton = require(script.MusicUtility.OverflowButton),
}
