[package]
name = "CorePackages"
authors = ["Roblox"]
license = ""
version = "0.1.0"

[config]
registry_index = { url = "https://apis.simulprod.com/rotriever-registry", protocol = "zip" }

[dependencies]
Rodux = "1.0"
RoactRodux = "0.2"
RoactAppExperiment = "0.4.1"
RoactNavigation = "0.5.10"
Cryo = "1.1.0"
Dash = "0.1"
llama = "1.0.0"
LuaSocialLibrariesDeps = "1.5.5"
AvatarExperienceDeps = "0.0.1"
UIBlox = "0.2.36"
Foundation = "1.9.0"
FoundationImages = "1.13.0"
Thumbnailing = "0.3.0"
Otter = "1.2.1"
ReactOtter = "1.2.1"
t = "3.0.0"
enumerate = "1.0.0"
PolicyProvider = { version = "0.1.2", package = "LuaRoactPolicyProvider" }
Lumberyak = { version = "0.1.1", package = "lumberyak" }
StringUtilities = { version = "1.0.0", package = "string-utilities" }
UrlBuilder = "1.2.4"
FitFrame = { version = "2.0.0", package = "RoactFitComponents" }
NetworkingFriends = "2.12.1"
EmojiList = "1.0.0"
RoduxGames = "1.4.1"
ReactFocusNavigation = "1.3.1"
InputHandlers = "1.3.1"
Roact = { version = "17.1.6", package = "RoactCompat" }
React = "17.1.6"
ReactIs = "17.1.6"
ReactRoblox = "17.1.6"
ReactSceneUnderstanding = "0.8.0"
ReactUtils = "1.2.0"
Promise = "3.5.0"
VirtualizedList = "1.4.3"
LuauPolyfill = "0.4.0"
RegExp = "0.2.1"
RoduxNetworking = "3.4.1"
NetworkingGames = "1.2.0"
NetworkingUsers = "1.2.1"
HttpRequest = "1.1.1"
ApolloClient = "0.3.10"
GraphQL = "15.6.3"
QRCode = "0.1.0"
Merge = "0.3.1"
GraphqlToolsUtils = { version = "0.3.1", package = "Utils" }
DataLoader = "0.2.0"
UGCValidation = "1.13.2"
RoduxPresence = "3.2.3"
RoduxFriends = "4.3.0"
RoduxUsers = "1.5.1"
RoduxContacts = "0.9.1"
Signal = "1.0"

# The following packages were ported from AppTempCommon
Result = { version = "0.1.0", package = "lua-result" }
tutils = "0.1.2"

InGameMenuDependencies = "0.3.0"

RoactGamepad = "0.5.13"

[dev_dependencies]
Jest = "3.8.1"
JestBenchmark = "3.8.1"
JestGlobals = "2.4.1"
JestGlobals3 = { version = "3.8.1", package = "JestGlobals" }
# switch from git-dependency once mirrored in artifactory
ReactTestingLibrary = "12.2.0"
Rhodium = "0.5.0"
TagUtils = "0.1.0"
RecordPlayback = "0.1.1"
RoduxDevtools = "1.0.0-rc.1"
# Dependencies for the Roact17 inspector
ReactDevtoolsExtensions = "17.1.6"
DeveloperTools = "0.2.7"
ApolloClientTesting = "0.3.10"
UsageTracker = "0.1.1"
ReactTestingUtils = "1.2.0"

# Patch all dependencies (git or otherwise) upon rodux to the flagged indirection package,
# which will ensure that we always use only one rodux version
[config.patch."https://github.com/roblox/rodux"]
Rodux = "3.2.0"

[config.patch."https://github.com/roblox/roblox-lua-promise"]
Promise = "3.5.0"

[config.patch."https://github.com/roblox/roact-navigation"]
RoactNavigation = "0.5.10"

# Roact 17 - Patch in roact compat for legacy roact
[config.patch."github.com/roblox/roact"]
Roact = { version = "17.1.6", package = "RoactCompat" }

[config.patch."github.com/roblox/roact-rodux"]
RoactRodux = "0.5.1"

# Patch over a deep jest dependency in order to preempt a new analysis error
# that caught several mistranslation bugs
[config.patch."github.com/roblox/picomatch-lua"]
Picomatch = "0.3.1"
